hw5 task2 decorator for custom_sum func and tests
IuliiaLanchuk/hometasksEpam pull request #23
Opened 2021-03-22 19:05 UTC by IuliiaLanchuk

2021-03-22 21:02 UTC, Cjkjvfnby requested changes
You have not met the task requirements.

2021-03-22 21:02 UTC, Cjkjvfnby commented on homework5/project2_save_original_info/task2_oop/save_original_info.py
> +декоратора на строку отведенную под него - замените комментарий
> замените комментарий

Why you neglect this requirement?

2021-03-23 05:42 UTC, IuliiaLanchuk commented on homework5/project2_save_original_info/task2_oop/save_original_info.py
> +декоратора на строку отведенную под него - замените комментарий
Sorry, I suppose this is just a comment. I have already replaced it with decorator.

2021-03-23 20:26 UTC, Cjkjvfnby approved these changes

2021-03-26 08:31 UTC, merged